<?php

return [
	"33-39 Drapery, Northampton NN1 2EZ, Royaume-Uni",
	"17 Limetree Cres, Cockermouth CA13 9HW, Royaume-Uni",
	"Town and Country Trail, Ross-on-Wye HR9 7NH, Royaume-Uni",
	"Albert Hotel, 1 Finkle St, Saint Bees CA27 0BN, Royaume-Uni",
	"2 Stephens Ln, Evendine Ln, Colwall Green, Malvern WR13 6EA, Royaume-Uni",
	"29 Wingate Rd, Trimdon Station TS29 6BT, Royaume-Uni",
	"8 Longmeadow Rd, Lympstone, Exmouth EX8, Royaume-Uni",
	"93 The Greenway, London NW9 5AR, Royaume-Uni",
	"7 Twyver Pl, Brockworth, Gloucester GL3 4AN, Royaume-Uni",
	"4 Saw Mill Cl, Walsall WS4 2LX, Royaume-Uni",
	"9 Austin Cl, Leyland PR25 3FG, Royaume-Uni",
	"2 Mill Ln, Wheaton Aston, Stafford ST19 9NL, Royaume-Uni",
	"5 Latham Rd, Selsey, Chichester PO20, Royaume-Uni",
	"47 Brinsea Rd, Congresbury, Bristol BS49 5JQ, Royaume-Uni",
	"4 W End, Lifton PL16 0BX, Royaume-Uni",
	"18 Highthorne St, Leeds LS12 3LB, Royaume-Uni",
	"5 Brighton Pl, Canonbie DG14 0UR, Royaume-Uni",
	"11 Old School Cl, Caversfield, Bicester OX27 8TW, Royaume-Uni",
	"32 Bearing Way, Chigwell IG7 4NB, Royaume-Uni",
	"21 Wentworth Ave, Luton LU4 9EN, Royaume-Uni",
	"Unnamed Road, Peterculter AB14 0PL, Royaume-Uni",
	"2 Kellah Farm Cottages, Kellah, Haltwhistle NE49 0JL, Royaume-Uni",
	"5 Mill Hall, Aylesford ME20 7GB, Royaume-Uni",
	"17 Ludgate Hill, Birmingham B3 1DW, Royaume-Uni",
	"48 Globe Ct, East Kilbride, Glasgow G74 3QZ, Royaume-Uni",
	"2 Spencer Cl, Ryde PO33 3AW, Royaume-Uni",
	"30 The Millrace, Polegate BN26 5LP, Royaume-Uni",
	"24 Bro Deg, Flint CH6 5XW, Royaume-Uni",
	"3 Mill Farm Cottages, Lower Sticker, Saint Austell PL26 7JL, Royaume-Uni",
	"William St, Workington CA14 3YJ, Royaume-Uni",
	"58 New Rowley Rd, Dudley DY2 8AT, Royaume-Uni",
	"1 Spinningfield Way, Heywood OL10 2LF, Royaume-Uni",
	"12 Longview Ave, Rainhill, Prescot L35 8LY, Royaume-Uni",
	"65 Knighton Park Rd, London SE26 5RN, Royaume-Uni",
	"7 Stoneycroft, Aldbury, Tring HP23 5RL, Royaume-Uni",
	"Unnamed Road, Rhosgoch LL66 0AU, Royaume-Uni",
	"2 Barons Hill Ave, Linlithgow EH49 7JU, Royaume-Uni",
	"Cygnus Way, Brackley NN13 6GF, Royaume-Uni",
	"6 Park Cl, Gosberton, Spalding PE11 4FA, Royaume-Uni",
	"David St, Stockport SK5 6AS, Royaume-Uni",
	"43B Penley's Grove St, York YO31 7PW, Royaume-Uni",
	"5 Argyll Rd, Fort William PH33 6LF, Royaume-Uni",
	"41 West St, Aldbourne, Marlborough SN8 2BS, Royaume-Uni",
	"22 Durley Cl, South Benfleet, Benfleet SS7 1HJ, Royaume-Uni",
	"4 Higher Trevorian Barns, St Buryan, Penzance TR19 6EA, Royaume-Uni",
	"15 Stadium Rd, Bristol BS6 7YD, Royaume-Uni",
	"3 Barclay Rd, Longridge, Preston PR3 3LD, Royaume-Uni",
	"89E Green Ln, Derby DE1 1RX, Royaume-Uni",
	"17A First St, Chelsea, London SW3 2LB, Royaume-Uni",
	"Leslie Yoxall Dr, Loughborough LE11 2GY, Royaume-Uni",
	"87 Castle Ln, Hadleigh, Benfleet SS7 2AL, Royaume-Uni",
	"2 Stafford Terrace, Brora KW9 6QW, Royaume-Uni",
	"13 Edgcumbe Rd, Lostwithiel PL22 0HZ, Royaume-Uni",
	"B6274, Richmond DL11 7QH, Royaume-Uni",
	"99 Greenleaf Gardens, Polegate BN26 6PH, Royaume-Uni",
	"12 Rigby St, Ashton-in-Makerfield, Wigan WN4 9PY, Royaume-Uni",
	"11 Parc Yr Onnen, Dinas Cross, Newport SA42 0SU, Royaume-Uni",
	"St Mary Rd, Weymouth DT4, Royaume-Uni",
	"Prince Phillip Lodge, 1 Admiral Moore Dr, Royal British Legion Village, Aylesford ME20 7SE, Royaume-Uni",
	"A701, Moffat DG10, Royaume-Uni",
	"82 Northfield Cres, Edinburgh EH8 7QB, Royaume-Uni",
	"11 Eaton Terrace Mews, Belgravia, London SW1W, Royaume-Uni",
	"9 Challis Ave, St Mawgan, Newquay TR8 4EJ, Royaume-Uni",
	"3 Prospect Ave, Attleborough NR17 2BZ, Royaume-Uni",
	"3 Arthur St Ln, Edinburgh EH6, Royaume-Uni",
	"4 Rowley Rd, Cottingham HU20, Royaume-Uni",
	"6 Wintonhill Cottages, Pencaitland, Tranent EH34 5AY, Royaume-Uni",
	"Cockmill Ln, Shepton Mallet BA4 4HR, Royaume-Uni",
	"107 Shakerley Rd, Tyldesley, Manchester M29 8ES, Royaume-Uni",
	"439 Gerald Rd, Haverfordwest SA61 2TN, Royaume-Uni",
	"28 Earlsway, Gateshead NE11, Royaume-Uni",
	"11-21 Edna Ave, Liverpool L10, Royaume-Uni",
	"39 Clockburnsyde Cl, Whickham, Newcastle upon Tyne NE16 5UT, Royaume-Uni",
	"13 Melford Ave, Shotts ML7 5HF, Royaume-Uni",
	"2 Deerdykes Ct N, Cumbernauld, Glasgow G68 9FL, Royaume-Uni",
	"62 Throop Rd, Bournemouth BH8 0LN, Royaume-Uni",
	"11 Sharnford Rd, Sapcote, Leicester LE9 4JN, Royaume-Uni",
	"7 Rampton Rd, Longstanton, Cambridge CB24 3EN, Royaume-Uni",
	"5 Stumperlowe Hall Chase, Sheffield S10 3QY, Royaume-Uni",
	"12 Barley Horn Rd, Ulleskelf, Tadcaster LS24 9DP, Royaume-Uni",
	"10 Patterson Cl, Madley, Hereford HR2 9PQ, Royaume-Uni",
	"11 Diana Cl, London E18 1DH, Royaume-Uni",
	"Fifth Ave, Nottingham NG9, Royaume-Uni",
	"2 Marina Terrace, Penysarn LL69 9BQ, Royaume-Uni",
	"1 S Common Farm Cottages, Selkirk TD7 4NW, Royaume-Uni",
	"Bavaria Rd, London N19 4EY, Royaume-Uni",
	"3 Greenhill Cres, Watford WD18 8JG, Royaume-Uni",
	"53-79 Tachbrook St, Pimlico, London SW1V, Royaume-Uni",
	"25 Stour Cl, West End, Southampton SO18 3LL, Royaume-Uni",
	"20 Church Ln, Ash Magna, Whitchurch SY13 4EA, Royaume-Uni",
	"21 Danestrete, Stevenage SG1, Royaume-Uni",
	"353 Upper Balsall Heath Rd, Birmingham B12, Royaume-Uni",
	"5 The Broadway, Totland Bay PO39, Royaume-Uni",
	"13 Ross Way, Folkestone CT20, Royaume-Uni",
	"8-12 Newton Grove, Newton Mearns, Glasgow G77, Royaume-Uni",
	"9 Lattimore Rd, Wheathampstead, St Albans AL4 8QF, Royaume-Uni",
	"20 Tanyard Cl, Alvechurch, Birmingham B48 7UA, Royaume-Uni",
	"B6357, Canonbie DG14 0RD, Royaume-Uni",
	"Golfhill Nursing Home, 35 Hanson St, Glasgow G31 2HG, Royaume-Uni",
	"45A Croila Rd, Kingussie PH21 1PB, Royaume-Uni",
];